#!/usr/bin/env node
/**
 * public/images/complete 안의 `숫자.확장자` 파일을 읽어
 * 숫자 오름차순으로 src/lib/album.generated.ts 를 생성한다.
 * 파일 이름(숫자)만 바꾸면 앨범 순서가 바뀐다 → npm run sync:album 후 빌드.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'public/images/complete');
const out = path.join(root, 'src/lib/album.generated.ts');

const files = fs
  .readdirSync(dir)
  .filter(name => /^\d+\.(jpe?g|png|webp)$/i.test(name))
  .sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10));

if (files.length === 0) {
  console.error('No numbered photos found in public/images/complete (e.g. 1.JPG)');
  process.exit(1);
}

const body = `/** Auto-generated by \`npm run sync:album\` — do not edit by hand. */
export const ALBUM_FILES = ${JSON.stringify(files, null, 2)} as const;
`;

fs.writeFileSync(out, body);
console.log(`Wrote ${files.length} album files → src/lib/album.generated.ts`);
console.log(files.join(', '));
